### PR TITLE
Refactor Dice model

### PR DESCRIPTION
**Pull request by angelocordon**
Refactor Dice model. 
Add RSpec testing framework.
Update Docker and Gemfile to use Ruby 2.5.0.

### CODE REVIEW

**Comment by angelocordon** [comment]
@tyberious-1 - I want to propose some changes in how the `Dice` model could/should work based off of your PR (#15). The main change here is the way we may be able to use a Dice model to call `Dice.roll` in any situations.

By default, it will roll a one six-sided dice (we can change this to whatever we think makes sense), but if we ever need a D20 dice for example, we'd just use the method as follows:

```ruby
Dice.roll(number_of_sides: 20)
```

Which will return us a value from a simulated one twenty-sided dice roll. 

Thoughts?

**Comment by tyberious-1** [comment]
A d6 is not really rolled that often a default d20 would be better

**Review by stain88 — CHANGES_REQUESTED** [review]
This does feel more appropriate laid out like this.

Agreed with @tyberious-1 in that 1D20 should be the default, so that needs updating.

Are we likely to ever call `#simulate_roll` by itself? It's no different to just calling `Dice.roll()`, with one die. In which case, I would put `rand(1..number_of_sides)` inside the block.

**Comment by stain88** [comment]
Also, would a modifier be applied to each roll individually, or to the total sum? If the former, that could be a use-case for `#simulate_roll`, and tie in a `min`/`max` type thing.

**Comment by tyberious-1** [comment]
> 
> 
> Also, would a modifier be applied to each roll individually, or to the total sum? If the former, that could be a use-case for `#simulate_roll`, and tie in a `min`/`max` type thing.

The modifiers are applied to the total not to individual rolls.

**Review by tyberious-1 — APPROVED** [review]
This needs to be change to roll  1d20 later instead of the 1d6 as a default value.

**Pull request merged**
